# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "oraclelinux/9"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.ssh.insert_key = false

  # VM01
  config.vm.define "vm01" do |vm01|
    vm01.vm.hostname = "vm01"
    vm01.vm.network "public_network",
      ip: "192.168.51.11",
      netmask: "255.255.255.224",
      bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

    vm01.vm.provider "virtualbox" do |vb|
      vb.name = "vm01"
    end

    vm01.vm.provision "shell", inline: <<-SHELL
      echo "Configurando vm01..."
      hostnamectl set-hostname vm01
    SHELL
  end

  # VM02
  config.vm.define "vm02" do |vm02|
    vm02.vm.hostname = "vm02"
    vm02.vm.network "public_network",
      ip: "192.168.51.12",
      netmask: "255.255.255.224",
      bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

    vm02.vm.provider "virtualbox" do |vb|
      vb.name = "vm02"
      vb.memory = 2048
    end

    vm02.vm.provision "shell", inline: <<-SHELL
      echo "Configurando vm02..."
      hostnamectl set-hostname vm02
    SHELL
  end

  # VM03
  config.vm.define "vm03" do |vm03|
    vm03.vm.hostname = "vm03"
    vm03.vm.network "public_network",
      ip: "192.168.51.13",
      netmask: "255.255.255.224",
      bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

    vm03.vm.provider "virtualbox" do |vb|
      vb.name = "vm03"
    end

    vm03.vm.provision "shell", inline: <<-SHELL
      echo "Configurando vm03..."
      hostnamectl set-hostname vm03
    SHELL
  end

end
