all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: /mnt/c/Users/lucas/.vagrant.d/insecure_private_keys/vagrant.key.ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: yes
    ansible_become_method: sudo

  children:
    vms:
      hosts:
        vm01:
          ansible_host: 192.168.51.11
          keepalived_state: MASTER
          keepalived_priority: 110
        vm02:
          ansible_host: 192.168.51.12
          keepalived_state: BACKUP
          keepalived_priority: 100
        vm03:
          ansible_host: 192.168.51.13
          keepalived_state: BACKUP
          keepalived_priority: 90

    vm01_group:
      hosts:
        vm01:

    vm02_group:
      hosts:
        vm02:

    vm03_group:
      hosts:
        vm03:
